### ISSUE TITLE
Keyboard LEDs

### ISSUE THREAD

**Issue by mekb-turtle** [caffeine-ng/caffeine-ng#108]
is it possible to have the scroll lock LED on if caffeine is enabled and off if it isn't?

**Comment by WhyNotHugo** [comment]
Trick given the current architecture.

Hooks to run could be implemented, but I intend to rewrite the surrounding parts, so might keep that in mind when doing so.

Won't promise anything for tho.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/108
