### ISSUE TITLE
Can't turn off startup notification (gnome)

### ISSUE THREAD

**Issue by colopatiron** [caffeine-ng/caffeine-ng#109]
I accidentally turned on the notification option and turned off the tray icon the last time I configured caffeine-ng. Now I can't turn off the notification since the -p switch (which the notif message advises you to do) does NOT work and I can't seem to find a way to go to the caffeine-ng settings again without the tray icon.

Any help would be appreciated.

**Comment by WhyNotHugo** [comment]
As a workaround, you can use `dconf-editor` to edit caffeine's preferences. They're stored (for historical reasons) in `/net/launchpad/caffeine/`. This is **not** a file path; this is the path of a dconf setting.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/109
