### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DamienCassou** [caffeine-ng/caffeine-ng#110]
It seems a few people have issues with audio playback detection which seems to be fixed in the main branch. Would you mind considering releasing caffeine-ng please? Thank you.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/110
