### ISSUE TITLE
Exception: Can't determine get_base_path()

### ISSUE THREAD

**Issue by icf20** [caffeine-ng/caffeine-ng#15]
```
caffeine

Traceback (most recent call last):
  File "/usr/local/bin/caffeine", line 7, in <module>
    from caffeine.main import main
  File "/usr/local/lib/python3.6/dist-packages/caffeine/__init__.py", line 23, in <module>
    from .paths import get_base_path
  File "/usr/local/lib/python3.6/dist-packages/caffeine/paths.py", line 57, in <module>
    __glade_path = join(get_base_path(), 'share', 'caffeine', 'glade')
  File "/usr/local/lib/python3.6/dist-packages/caffeine/paths.py", line 33, in get_base_path
    raise Exception("Can't determine get_base_path()")
Exception: Can't determine get_base_path()
```

any idea how to fix this?

**Comment by WhyNotHugo** [comment]
How did you install caffeine? What distro is this?

**Comment by rodolfovalentim** [comment]
same problem in xubuntu 16.04

**Comment by marzipankaiser** [comment]
It seems that `get_base_path()` searches from `paths.py` upwards for a directory containing `share/caffeine`, which does not necessarily exist. 

Adding a symlink `site-packages/share` -> `site-packages/usr/share` (which was the correct directory on my system - it should contain subdirectories `caffeine`, `icons` and others) fixed this for me. 
(Although I still have other errors with Xlib not being able to connect to the display -- which seems unrelated for me)

**Comment by WhyNotHugo** [comment]
@marzipankaiser That's really odd; `share/caffeine` (generally `/usr/share/caffeine`) should be created during installation. Can you tell me exactly how you installed caffeine?

**Comment by marzipankaiser** [comment]
@WhyNotHugo I am currently trying to package `caffeine-ng` for [NixOS](https://nixos.org/), which does not adhere to the FHS (To allow for some fancy stuff) and where much of the installation process is done by standard python packaging functions (In this case `buildPythonApplication`. So I don't know the exact commands they execute - but it should be the standard Python setuptools commands). I can look into the details of those later (they might be the problem for me).

However, looking at the code, the given exception should be raised iff this path is not existent in any parent directory, so this seems to be the problem. Were there any changes to path names recently?

**Comment by WhyNotHugo** [comment]
Yeah, the way caffeine currently works is by looking for something like `/usr/share/caffeine` or `/usr/local/share/caffeine` or alike. On non FHS hierarchies that might be an issue.

TBH, the way caffeine is installed has been a pain point for a long time, and I've wanted to change that for a long time. I'd love to make it a "plain python package", but the desktop file and its icons have to be placed elsewhere -- which is kinda annoying.

How are you handling the `.desktop` file on NixOS?

**Comment by marzipankaiser** [comment]
@WhyNotHugo Currently not. Thats an issue for when I can run it from the console (there are still some issues regarding the environment variables etc - I am still a noob with NixOS packaging)...

**Comment by WhyNotHugo** [comment]
I've just landed a fix on `master`, can you install that and confirm it fixes the issue?

**Comment by WhyNotHugo** [comment]
@marzipankaiser ?

**Comment by marzipankaiser** [comment]
Oh, sorry. Completely forgot this... I am currently busy. I did however get the package working using the old version (see https://github.com/NixOS/nixpkgs/pull/61676).

I have not yet managed to build the project from current master, since setuptools needs an intact `.git` folder to build the project, which I did not yet manage to do - mostly because `.git`-folders are non-deterministic (see https://github.com/NixOS/nixpkgs/issues/8567) which makes NixOS packaging this quite hard... I will try to look into this once I find time.

**Comment by marzipankaiser** [comment]
Update: Found some time. Using a hack to make setuptools work (essentially, copying the PKG-INFO etc from the current PyPI release into the git tarball), the new version can be made to work with similar effort (I still needed to copy some assets "manually" (specifically the `caffeine/assets` and `share` folders), however, this could also be a issue related to NixOS)

**Comment by WhyNotHugo** [comment]
I can create a beta release if it makes your life any easier. That should push release packages to PyPI and GitHub.

**Comment by WhyNotHugo** [comment]
Why do you need to copy them manually? Where do they get installed and where do you need them? They _should_ end up inside the python package, so no shuffling should be necessary.

**Comment by marzipankaiser** [comment]
only the `caffeine/assets/icons subfolder` ends up inside the package. Both the glade and the `glade` and `images` subfolders (that should end up in `./lib/python2.7/site-packages/caffeine/assets`) do not exist in the generated package, so I had to copy them manually. Apart from that, the changed version works out of the box (modulo some things that are needed for any Nix package using Glib etc)

Since I now know how to trick setuptools into working with random git checkouts, a beta release is not necessary. But thank you.

**Comment by WhyNotHugo** [comment]
Can you double check that? They're in the package for me:

```
$ unzip caffeine_ng-3.4.2.post22+g4ec5e87.d20190612-py3-none-any.whl                                                                                                                                
Archive:  caffeine_ng-3.4.2.post22+g4ec5e87.d20190612-py3-none-any.whl                                                                                                                              
   creating: caffeine/                                                                                                                                                                              
   creating: caffeine_ng-3.4.2.post22+g4ec5e87.d20190612.data/                                                                                                                                      
   creating: caffeine_ng-3.4.2.post22+g4ec5e87.d20190612.dist-info/                                                                                                                                 
   creating: etc/                                                                                                                                                                                   
   creating: usr/                                                                                                                                                                                   
   creating: caffeine/assets/
   creating: caffeine/locale/
  inflating: caffeine/__init__.py    
  inflating: caffeine/__main__.py    
  inflating: caffeine/applicationinstance.py  
  inflating: caffeine/core.py        
  inflating: caffeine/icons.py       
  inflating: caffeine/inhibitors.py  
  inflating: caffeine/main.py        
  inflating: caffeine/paths.py       
  inflating: caffeine/procmanager.py  
  inflating: caffeine/utils.py       
  inflating: caffeine/version.py     
   creating: caffeine/assets/glade/
   creating: caffeine/assets/icons/
   creating: caffeine/assets/images/
  inflating: caffeine/assets/glade/GUI.glade  
  inflating: caffeine/assets/glade/proc.glade  
   creating: caffeine/assets/icons/hicolor/
   creating: caffeine/assets/icons/ubuntu-mono-dark/
   creating: caffeine/assets/icons/hicolor/16x16/ 
   creating: caffeine/assets/icons/hicolor/22x22/ 
   creating: caffeine/assets/icons/hicolor/24x24/ 
   creating: caffeine/assets/icons/hicolor/32x32/ 
   creating: caffeine/assets/icons/hicolor/48x48/ 
   creating: caffeine/assets/icons/hicolor/scalable/
   creating: caffeine/assets/icons/hicolor/16x16/apps/
   creating: caffeine/assets/icons/hicolor/16x16/status/
  inflating: caffeine/assets/icons/hicolor/16x16/apps/caffeine.png  
  inflating: caffeine/assets/icons/hicolor/16x16/status/caffeine-cup-empty.png  
  inflating: caffeine/assets/icons/hicolor/16x16/status/caffeine-cup-full.png  
```

Also, you're using python2. That has never been supported by caffeine, it's always been python3 (I'm surprised it even runs). I don't think that's the issue, but do keep that in mind.

**Comment by JcKlomp** [comment]
This is still an issue. Every new python version it is necessary to create a symlink: `ln -s ~/.local/lib/python3.8/site-packages/usr/share ~/.local/lib/python3.8/site-packages/share`

**Comment by WhyNotHugo** [comment]
If you upgrade your python version, you need to reinstall python packages.

There's nothing that can be done about this, and applies to any python package. It's up to the package maintainers to do this.
