### ISSUE TITLE
Enable caffeine-ng if CPU load is >95%

### ISSUE THREAD

**Issue by PF4Public** [caffeine-ng/caffeine-ng#16]
Feature request for additional configuration option, that enables caffeine if CPU load is more than, say, 95%
This probably needs to be thinked through though, but I think this feature might be handy while performing some long CPU-intensive tasks, like building kernel for example

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/16
