### ISSUE TITLE
Allow inhibiting suspend, but not a screensaver

### ISSUE THREAD

**Issue by PF4Public** [caffeine-ng/caffeine-ng#2]
It would be great if it would be possible to specify which inhibitor an aplication is associated with while adding an application.
This could be accomplished by clasifying all inhibitors as 'power' and 'screensaver' and allowing to choose, which of them to use while adding an application.
This is useful for a torrent-client, for example. Even though caffeine is unable to identify any activity in that aplication, still this would be useful. Other example would be a media player, which should allow for a screensaver, but prevents suspend.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/2
