### ISSUE TITLE
Add option to inhibit while sound is playing

### ISSUE THREAD

**Issue by Tank-Missile** [caffeine-ng/caffeine-ng#21]
If you're watching a video or listening to music in the background, there is little reason for inhibition. Of course, it should follow the blacklist/whitelist to determine which programs to watch for.

**Comment by WhyNotHugo** [comment]
I don't think it's trivial to implement this (not sure how to detect if sound is playing).

Watching a fullscreen video should trigger caffeine. Not sure what the rational behind background music and keeping the screen on is though.

**Comment by Tank-Missile** [comment]
Well, if I'm doing something else while the sound is playing, and there's no fullscreen, suspend will eventually kick in. It's a hypothetical situation, but having it as an option wouldn't hurt. As for how to detect sound, I know pulseaudio provides a way to detect current sink inputs (playback) from any application running, and it can be distinguished which application is producing the sound. As for detection with ALSA for those who don't use pulseaudio, I'm not too sure.

**Comment by g0r3** [comment]
@WhyNotHugo: Are other users not allowed to create branches? I did a patch for this for this feature and I don't have the permissions to create a branch for a pull request. Or am I just a total github noob and fail to use it?

**Comment by WhyNotHugo** [comment]
@g0r3 You need to create a fork, and push your changes there. [This guide](https://help.github.com/en/articles/fork-a-repo) should help you through it.

Let me know if you have any questions.

**Comment by g0r3** [comment]
Ohhh... yes, now I got it. I was just used to branch of master.
https://github.com/caffeine-ng/caffeine-ng/pull/34#issue-310990092

I did some more work since I created my posting. Now Caffeine is also able to turn the screen off, if there is only audio playing but nothing else, a feature also requested here (https://github.com/caffeine-ng/caffeine-ng/issues/2) Not sure if my detection method works for all music players, but time will tell :) But if not it always will keep the screen on.

I also hope the logic for the screensave is ok. Had my problems to wrap my head around the toggle system :D I'm was testing it and am using it now on my system and everything seems to work as it should.

**Comment by Tank-Missile** [comment]
I'm testing out the latest git, and it works great about 90% of the time. The other 10%, it gets stuck inhibiting. Whenever I try to disable it, it just renables itself a few seconds later. There are no audio sources playing when this occurs. The only way to fix it at that point is to play and then stop an audio source, and then wait for caffeine to auto-disable. Restarting the application does not fix the issue, as it will just auto-enable itself even when there are no audio sources. This also seems to occur on login, and once again, the only fix is the one I stated above. It could be the login sound I have enabled that's causing it, but I'm not sure.

**Comment by g0r3** [comment]
> There are no audio sources playing when this occurs.

This means, that the output of pacmd list-sink-inputs as well as pacmd list-source-outputs is empty while Caffeine is inhibiting? Did you let it log into a file to see the exact reason why Caffeine is inhibiting? When you know that you could add some debug output. I cannot confirm the behavior described by you on my system, but if the Pulseaudio part is working correctly there might be a flaw in the logic.

**Comment by Tank-Missile** [comment]
pacmd list-sink-inputs:
```
2 sink input(s) available.
    index: 0
        driver: <module-combine-sink.c>
        flags: VARIABLE_RATE DONT_MOVE NO_CREATE_SUSPEND 
        state: DRAINED
        sink: 0 <alsa_output.usb-Razer_Razer_Kraken_7.1_V2_00000000-00.analog-stereo>
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        muted: no
        current latency: 0.00 ms
        requested latency: 100.14 ms
        sample spec: s16le 2ch 44023Hz
        channel map: front-left,front-right
                     Stereo
        resample method: trivial
        module: 24
        properties:
                media.name = "Simultaneous output on Razer Kraken 7.1 V2 Analog Stereo"
                media.role = "filter"
                module-stream-restore.id = "sink-input-by-media-role:filter"
    index: 1
        driver: <module-combine-sink.c>
        flags: VARIABLE_RATE DONT_MOVE NO_CREATE_SUSPEND 
        state: DRAINED
        sink: 1 <alsa_output.pci-0000_24_00.3.analog-stereo>
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        muted: no
        current latency: 0.00 ms
        requested latency: 100.14 ms
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        resample method: trivial
        module: 24
        properties:
                media.name = "Simultaneous output on Family 17h (Models 00h-0fh) HD Audio Controller Analog Stereo"
                media.role = "filter"
                module-stream-restore.id = "sink-input-by-media-role:filter"
```
pacmd list-source-outputs:
```
1 source output(s) available.
    index: 0
        driver: <module-remap-source.c>
        flags: START_CORKED 
        state: CORKED
        source: 3 <micspam_output.monitor>
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        muted: no
        current latency: 0.00 ms
        requested latency: n/a
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        resample method: (null)
        owner module: 25
        properties:
                media.name = "Remapped Stream"
                media.role = "filter"
                module-stream-restore.id = "source-output-by-media-role:filter"
```
caffeine log:
```
/usr/lib/python3.7/site-packages/caffeine/main.py:60: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
INFO:caffeine.core:Caffeine is starting up...
INFO:caffeine.core:Audio playback detected. Inhibiting.
INFO:caffeine.core:XdgPowerManagmentInhibitor is applicable, state: True
INFO:caffeine.core:XorgInhibitor is applicable, state: True
INFO:caffeine.core:XdgScreenSaverInhibitor is applicable, state: True
INFO:caffeine.core:DpmsInhibitor is applicable, state: True
INFO:caffeine.core:
```

**Comment by g0r3** [comment]
So you actually have processes which record/play audio. This looks like a instant audio passthrough from the mic to the speakers, so that you can hear the mic input over the speakers. Do you have set up something like that?

It is worth to have a discussion about how to handle this. Either ignore certain processes (the `media.role = "filter"` catches my eye here) or maybe add a GUI to allow the user himself to whitelist certain audio processes

**Comment by Tank-Missile** [comment]
It's a combined sink that I can set an audio source to, which is then remapped as an input device by using the sink's .monitor source. This allows me to treat the remapped source as a microphone for playing audio in voice applications.

**Comment by WhyNotHugo** [comment]
I'm kind of reluctant to add a GUI because I suck at using GTK. I'm happy to accept PRs for that, but maybe a config file might work for this (I'm more inclined towards config files myself too, tbh).

The same actually applies to whitelist/blacklist in general.

**Comment by Tank-Missile** [comment]
So I did some more testing, and it's diffidently the combined and remapped sinks that are causing caffeine to activate on login. In fact, simply creating the combined sink and remapped sink with pacmd is enough to trigger it. This is my ~/.config/pulse/default.pa file:

```
.include /etc/pulse/default.pa

load-module module-combine-sink sink_name=micspam_output sink_properties=device.description=Micspam
load-module module-remap-source source_name=micspam_input source_properties=device.description=Micspam master=micspam_output.monitor
```

If I remove the combined and remapped sink, the issue no longer occurs. I'll try to see what I can do to figure out what's going on.

**Comment by g0r3** [comment]
Did you check the behavior of pulsectl? Because I had a look into pulsectl and it doesn't seem to enumerate every possible state of sinks/sources:
```Python
PA_OBJ_STATE_MAP = c_enum_map(invalid=-1, running=0, idle=1, suspended=2)
```
in https://github.com/mk-fg/python-pulse-control/blob/master/pulsectl/_pulsectl.py#L127

It could very well be, that it just treats every state except _invalid_, _idle_ and _suspended_ as _running_.

**Comment by Tank-Missile** [comment]
I checked with the python-pulse-control developer, and this is not an issue on his end. I believe you were right about "filter" media.role. According to the "PulseAudio under the hood" page, "Virtual source or sink is not associated with an audio device. It may represent a remote network device, a sound processing filter, or anything else, depending on the implementation." Simply ignoring filters should fix the issue I'm having. There is no reason to track them in this application.

**Comment by Tank-Missile** [comment]
After having a discussion with the python-pulse-control developer, he has added support for retrieving peak samples. This is a much more accurate way to gauge if sound is playing than states. Here's example code below showing it off:

```python
from pulsectl import Pulse

with Pulse() as pulseaudio:
	for sink in pulseaudio.sink_input_list():
		sink_source = pulseaudio.sink_info(sink.sink).monitor_source
		sink_peak = pulseaudio.get_peak_sample(sink_source, 0.1)
		if sink_peak > 0:
			print("Audio source is playing.")
		else:
			print("Audio source is not playing.")
```
Pavucontrol uses peak samples to display volume meters for playing applications.

**Comment by VoodaGod** [comment]
@Tank-Missile in #57 i implemented your suggestion with a GUI toggle

**Comment by carlocastoldi** [comment]
We should close this issue, shouldn't we?
