### ISSUE TITLE
Add program blacklist

### ISSUE THREAD

**Issue by Tank-Missile** [caffeine-ng/caffeine-ng#22]
Some full screen programs I don't want caffeine to activate for, and so a blacklist on top of the already existing whitelist would allow for more flexibility.

**Comment by WhyNotHugo** [comment]
This repository has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/22
