### ISSUE TITLE
screen dimming in manjaro-XFCE 18  & possible "presentation mode" support?

### ISSUE THREAD

**Issue by carlinux** [caffeine-ng/caffeine-ng#23]
Apparently caffeine doesn't prevent xfce4-power-manager screen dimming (after x seconds) . in manjaro-XFCE. ( I'm not sure in other xfce distros. )
Extrangely enough, xfce4-power-manager knows that caffeine is preventing power management as you can see in the screenshot. 
![Captura de pantalla_2019-03-16_17-02-22](https://user-images.githubusercontent.com/20126890/54477958-5c30fd80-480d-11e9-965c-99512d4b4786.png)
(sorry it is in spanish, the message says "caffeine is preventing the use of PM"
On the other hand xfce4-power-manager now has a (less smart than caffeine) mode to prevent PM, it is called "presentation mode". That mode prevents PM while it is active. 

I wonder if it would be possible to integrate  "Presentation mode" as the PM for caffeine in XFCE.
it can be set in real time by summoning xfconf-query 
To trigger it on and off
`xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -T`
To explicitly  activate or deactivate it  
`xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s true`
`xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s false`

This mode prevents screen dimming and every other PM aspect. 

Thanks in advance

**Comment by carlinux** [comment]
First of all i'm not a coder so maybe i,m missing something important but just looking into the code I think this could do it.

```
class xfceInhibitor(BaseInhibitor):

    def __init__(self):
        BaseInhibitor.__init__(self)

    def inhibit(self):
        self.running = True

        os.system("xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s true")

    def uninhibit(self):
        self.running = False

        # FIXME: Aren't we enabling it if it was never online?
        # Grep `xset q` for "DPMS is Enabled"
        os.system("xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s false")

    @property
    def applicable(self):
        # TODO!
return True
```

**Comment by WhyNotHugo** [comment]
This repository has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/23
