### ISSUE TITLE
Allow left click on icon to toggle caffeine

### ISSUE THREAD

**Issue by whitman-colm** [caffeine-ng/caffeine-ng#26]
Hi, I'm not sure if this is a bug report or a feature request, but would it be possible to make it so that left-clicking the icon in the menu bar to turn it on/off instead of right clicking and toggling it that way? Currently you have to right-click and toggle it within the menu.

**Comment by WhyNotHugo** [comment]
Left click is the default unless you're using appindicators. Appindicators override this, so it's beyond our control.
