### ISSUE TITLE
Binary path is wrong in .desktop files

### ISSUE THREAD

**Issue by PF4Public** [caffeine-ng/caffeine-ng#3]
Installing under some distributions puts binary in `/usr/local/bin`
At least that's true if using `checkinstall`
Using `--install-layout=deb` solves it for python 2.7, but python 3 still [fails copying files under checkinstall](https://superuser.com/q/1323719/187669)
I suggest keeping this issue open both for a [future person](https://xkcd.com/979/) and to keep record if a resolution will be available later.

**Comment by WhyNotHugo** [comment]
I've been thinking lately about changing the `setup.py` to a proper `Makefile`.

There's currently kind of a mess, since this is half a python package and half not, which makes finding files, and setting these sort of paths clumsy.

I'll make sure this gets addressed when changing that.

**Comment by PF4Public** [comment]
BTW, we can then integrate that huge `checkinstall` command from readme into the makefile, so as to call it simply `make deb`

**Comment by eyal0** [comment]
I think that in a related issue, I don't see the caffeine icons getting picked up correctly.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/3
