### ISSUE TITLE
Could we have a white icon for dark themes?

### ISSUE THREAD

**Issue by NerosTie** [caffeine-ng/caffeine-ng#33]
I'm on KDE and the default icon for caffeine is too dark with my theme (Breeze Dark). Could we have an option to put a white icon instead?

![Screenshot_20190625_170906](https://user-images.githubusercontent.com/4572452/60110170-f3421580-976b-11e9-99db-0dbf339a9e2d.png)

**Comment by WhyNotHugo** [comment]
It's really up to the icon theme you're using to provide a matching icon (much like it happens all your other taskbar icons). Apps don't generally handle this themselves.

If your icon doesn't provide an icon that matches in style, you can just drop on in into it's proper directory.
