### ISSUE TITLE
There's no fullscreen auto-activation option anymore

### ISSUE THREAD

**Issue by Amathadius** [caffeine-ng/caffeine-ng#36]
There's no fullscreen auto-activation option and caffeine does not activate in full screen anymore.

Archlinux & Manjaro
Kernel 5.3.1 & 5.2.11
Gnome 3.34 & 3.32

**Comment by WhyNotHugo** [comment]
This repository has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/36
