### ISSUE TITLE
Changing power source while Caffeine is enabled makes it behave like it's disabled

### ISSUE THREAD

**Issue by fdmarcin** [caffeine-ng/caffeine-ng#38]
Hi!
I'm on Manjaro XFCE and even though I don't experience #23, when I plug in or out a charger, Caffeine behaves like disabled.
The tray icon appears as enabled.
Toggling the tray icon off and back on makes it behave properly again.

```
OS: Manjaro Linux x86_64 
Host: Precision 7540 
Kernel: 5.4.2-1-MANJARO 
Resolution: 1920x1080 
DE: Xfce 
WM: Xfwm4 
WM Theme: Default 
Theme: Arc-Maia-Dark [GTK2], Adwaita [GTK3] 
Icons: Papirus-Dark [GTK2], Adwaita [GTK3] 
CPU: Intel i9-9880H (16) @ 4.800GHz 
GPU: Intel UHD Graphics 630 
```

**Comment by WhyNotHugo** [comment]
I'm pretty sure XFCE must trigger a reconfiguration of the power saving when the power source changes.

I'll have to think how to detect this and work around it.

**Comment by WhyNotHugo** [comment]
This repository has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/38
