### ISSUE TITLE
GTK-Critical under Wayland with scale factor

### ISSUE THREAD

**Issue by bpereto** [caffeine-ng/caffeine-ng#40]
I use Manjaro with Gnome Shell and Wayland. With a HiDPI Display and for resulution reasons I'm using Framebuffer scaling:

https://wiki.archlinux.org/index.php/HiDPI

> Enable the experimental fractional scaling feature:
$ gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"

```
~ >>> caffeine                                                            [127]
INFO:caffeine.core:Caffeine is starting up...

(caffeine:27844): Gtk-CRITICAL **: 13:34:04.780: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```
Caffeine Tray-Icon does not show up.

**Comment by WhyNotHugo** [comment]
You'll need to install `libappindicator-gtk3` on Wayland, since Xorg tray icons won't work.

That said, I'm not entirely sure if this will work on wayland as expected.

**Comment by bpereto** [comment]
Works like a charm. thx.
