### ISSUE TITLE
Caffeine-ng not working on Deepin desktop

### ISSUE THREAD

**Issue by burkusmax** [caffeine-ng/caffeine-ng#41]
I can't seem to get caffeine-ng to work on my Arch install with the Deepin Desktop Environment installed. 

The tray icon looks like it's activated, but it doesn't actually prevent suspend. 

I have DDE and Arch updated to latest.

**Comment by WhyNotHugo** [comment]
Can you run in a terminal and provide the output.

What handles screenlocking / screenblanking for you?

**Comment by WhyNotHugo** [comment]
This repository has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/41
