### ISSUE TITLE
Does caffeine-ng support gnome-wayland?

### ISSUE THREAD

**Issue by tkit1994** [caffeine-ng/caffeine-ng#44]
<details> <summary> My Environment</summary>
<p>

```
➜  ~ neofetch     
                   -`                    tkit@tkit-pc 
                  .o+`                   ------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Lenovo G480 Lenovo G480 
               `+oooooo:                 Kernel: 5.7.12-arch1-1 
               -+oooooo+:                Uptime: 24 mins 
             `/:-:++oooo+:               Packages: 1081 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1366x768 
          `/+++ooooooooooooo/`           DE: GNOME 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Arc 
       -osssssso.      :ssssssso.        Theme: Arc [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Numix-Circle [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i5-3210M (4) @ 3.100GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M 
 `++:.                           `-/+/   GPU: Intel 3rd Gen Core processor Graphics Controller 
 .`                                 `/   Memory: 2372MiB / 11878MiB 

                                                                 
                                            
➜  ~ gnome-shell --version
GNOME Shell 3.36.4
```
</p>
</details>

My caffeine-ng works well under gnome-x11, but under gnome-wayland the caffeine-ng tray-icon is nowhere to be found.

**Comment by tkit1994** [comment]
If i run caffeine from cli, there is a error 
```
Gtk-CRITICAL **: 20:20:26.397: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```
I ran the program with pdb line by line, [this line](https://github.com/caffeine-ng/caffeine-ng/blob/master/caffeine/main.py#L194) seems to cause the problem
same as #40 . 
Then I have libappindicator-gtk3 installed.
The error message is the same, but the [line](https://github.com/caffeine-ng/caffeine-ng/blob/master/caffeine/main.py#L462) that cause it differs from before.


I know little about gtk programming, so I gave up.

**Comment by davidde** [comment]
I recently ran into this error too on a clean Arch install. Just wanted to let people know it is pretty straightforward to fix:
* Install `libappindicator-gtk3`.
* Install the Gnome extension [appindicator-support](https://extensions.gnome.org/extension/615/appindicator-support/). This is required for system tray indicators in Gnome, and is likely not installed on a minimal OS install. Note this did not seem to work when installed through `yay`, so it's probably best to install directly from the extensions site. This will require `chrome-gnome-shell` to be installed, as well as a [Firefox](https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/) or [Chrome](https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep) addon to enable it.
* Reinstall `caffeine-ng`.

So I guess this issue can be closed, but it's probably a good idea to mention this in the README under a "Gnome Wayland" heading.

**Comment by tkit1994** [comment]
I will try that later, thanks for your advice. @davidde

**Comment by tkit1994** [comment]
Your solution works! @davidde 
By the way, the aur version of [gnome-shell-extension-appindicator-git](https://aur.archlinux.org/packages/gnome-shell-extension-appindicator-git/) works for me too
