### ISSUE TITLE
The icon doesn't appear on the status bar 

### ISSUE THREAD

**Issue by ghost** [caffeine-ng/caffeine-ng#46]
I have installed the app from the AUR and have enabled it on startup, but the tray icon doesn't show up.

**Comment by ngmoviedo** [comment]
Can reproduce, although it only happens occasionally. I'm also on Arch and installed it from the AUR. My WM is i3-gaps, and it is the responsible for the initialization of caffeine on startup. The tray is handled by Polybar.
As I said, it happens randomly. This is the output of manually starting it from the shell:

```
/usr/lib/python3.9/site-packages/caffeine/main.py:59: PyGIWarning: AppIndicator3 was importedwithout specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
INFO:caffeine.core:Caffeine is starting up...

(caffeine:2948): Gdk-CRITICAL **: 21:04:58.170: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by Inglebard** [comment]
Hi,
I have the same issue on gnome Manjaro.
The actual workaround for me is to modify ".config/autostart/caffeine.desktop" and change "Exec" to `Exec=sh -c "sleep 5 && /usr/bin/caffeine"`.
Look like the same bug as : https://github.com/moson-mo/mntray/issues/4

**Comment by WhyNotHugo** [comment]
Sounds like caffeine starts before the tray, so the tray is unavailable.

The proper fix would likely be for caffeine to retry this on failure.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/46
