### ISSUE TITLE
Expose "Use AppIndicator" as a toggle in preferences.

### ISSUE THREAD

**Issue by EquusRaphanus** [caffeine-ng/caffeine-ng#47]
I personally don't really understand or care what benefits there are to AppIndicator, to me it's more important to minimize interaction with UI. With a status_icon, the icon in the tray is left click on/off, right click to bring up the menu (1 click to activate). With AppIndicator, left or right click brings up the menu and you have to click activate (2 clicks).

I've made the following changes to main.py to force this behavior, but it'd be great if this were a user configurable option!

```
appindicator_avail = False
#appindicator_avail = True
#try:
#    from gi.repository import AppIndicator3
#except ImportError:
#    appindicator_avail = False
```

**Comment by WhyNotHugo** [comment]
Agree on the need for this flag -- many people have `AppIndicator` libraries installed, but want the features disabled.

I'd welcome a PR that adds a checkbox in preferences -- #74 can be merged after that.
