### ISSUE TITLE
Python 3 only?

### ISSUE THREAD

**Issue by PF4Public** [caffeine-ng/caffeine-ng#5]
Is there a reason for "Python 3" in requirements?
For me it works fine with Python 2.7.

**Comment by WhyNotHugo** [comment]
I don't think I've ever tested this with python2. At some point, one of the dependencies was python3-only.

TBH, considering so many projects are moving away from python2, I don't know if it's a good time to announce python2-support. This might break in future and I don't want to be committed to it.
