### ISSUE TITLE
[KDE] Doesn't run after install from offical repositories.

### ISSUE THREAD

**Issue by chrisfxwolf** [caffeine-ng/caffeine-ng#51]

**Comment by chrisfxwolf** [comment]
Hi,

This problem occur after install caffeine from official repositories by zypper:

`/usr/bin/caffeine:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.`
 ` from gi.repository import GObject, Gtk, GLib`
`Traceback (most recent call last):
  File "/usr/bin/caffeine", line 36, in <module>
    ewmh = EWMH()
  File "/usr/lib/python3.6/site-packages/ewmh.py", line 50, in __init__
    self.display = _display or display.Display()
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)`
`Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'`

According to the [openSUSE software](https://software.opensuse.org/package/caffeine) it should be working.

This is all Gtk which installed in my system:
`PackageKit-gtk4-module
at-spi2-atk-gtk2
gettext-its-gtk3
gnome-themes-accessibility-gtk2
gstreamer-plugins-good-gtk
gtk2-branding-openSUSE
gtk2-data
gtk2-engine-hcengine
gtk2-engine-murrine
gtk2-immodule-amharic
gtk2-immodule-inuktitut
gtk2-immodule-thai
gtk2-immodule-tigrigna
gtk2-immodule-vietnamese
gtk2-lang
gtk2-metatheme-adwaita
gtk2-metatheme-breeze
gtk2-metatheme-greybird-geeko
gtk2-theming-engine-adwaita
gtk2-tools
gtk3-branding-openSUSE
gtk3-data
gtk3-devel
gtk3-immodule-amharic
gtk3-immodule-inuktitut
gtk3-immodule-thai
gtk3-immodule-tigrigna
gtk3-immodule-vietnamese
gtk3-lang
gtk3-metatheme-adwaita
gtk3-metatheme-breeze
gtk3-metatheme-greybird-geeko
gtk3-schema
gtk3-tools
gtkspell-lang
kde-gtk-config5
kde-gtk-config5-gtk2
kde-gtk-config5-gtk3
libcanberra-gtk-module-common
libcanberra-gtk0
libcanberra-gtk2-module
libcanberra-gtk3-0
libcanberra-gtk3-module
libdbusmenu-gtk3-4
libgirara-gtk3-3
libgtk-2_0-0
libgtk-3-0
libgtkmm-2_4-1
libgtkspell0
libjavascriptcoregtk-4_0-18
libqt5-qtbase-platformtheme-gtk3
libqt5-qtstyleplugins-platformtheme-gtk2
libunity-gtk2-parser0
libunity-gtk3-parser0
libwebkit2gtk-4_0-37
libwebkit2gtk3-lang
libwx_gtk2u_adv-suse3
libwx_gtk2u_aui-suse3
libwx_gtk2u_core-suse3
libwx_gtk2u_gl-suse3
libwx_gtk2u_html-suse3
libwx_gtk2u_qa-suse3
libwx_gtk2u_xrc-suse3
lightdm-gtk-greeter
lightdm-gtk-greeter-branding-openSUSE
lightdm-gtk-greeter-lang
python-gtk
typelib-1_0-Gtk-3_0
unity-gtk-module-common
unity-gtk2-module
unity-gtk3-module
webkit2gtk-4_0-injected-bundles
xdg-desktop-portal-gtk
xdg-desktop-portal-gtk-lang`


..as well installed:
python-gobject2
- python ver. 3.6.12

There is:
> Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.`
 ` from gi.repository import GObject, Gtk, GLib`

Hmm... Any solutions?

My system is:
 - Operating System: openSUSE Leap 15.2
 - KDE Plasma Version: 5.18.6
 - KDE Frameworks Version: 5.71.0
 - Qt Version: 5.12.7
 - Kernel Version: 5.3.18-lp152.60-default
 - OS Type: 64-bit
 - Processors: 8 × Intel® Xeon® CPU W3530 @ 2.80GHz
 - Memory: 31.3 GiB of RAM

**Comment by WhyNotHugo** [comment]
Are you using KDE via Xorg or Wayland?

**Comment by chrisfxwolf** [comment]
Xorg according to terminal output:
`echo $XDG_SESSION_TYPE`
result:
`x11`

**Comment by chrisfxwolf** [comment]
Yes, python broken caffeine. However, I was back to Manjaro. OpenSUSE is fantastic, stability system but world is going faster, if you know what I mean.
