### ISSUE TITLE
Updated Python3 Debian/Ubuntu build

### ISSUE THREAD

**Issue by STrRedWolf** [caffeine-ng/caffeine-ng#52]
Some updates to your documentation.  Python 2 is being dropped for good.  You need to switch to Python 3.

So, to build it against Python 3 in Ubuntu (I used 20.10 on a Raspberry Pi 400):

```
sudo apt-get install python3-setuptools python3-pip checkinstall 
sudo apt-get install python3-docopt python3-ewmh python3-setproctitle python3-wheel python3-xdg
sudo apt-mark auto python3-docopt python3-ewmh python3-setproctitle python3-wheel python3-xdg
make build
make clean
sudo checkinstall --pkgname=caffeine-ng --pkgversion=3.4 --requires="python3-docopt,python3-ewmh,python3-setproctitle,python3-wheel,python3-xdg" --conflicts="caffeine" --nodoc python3 ./setup.py install --install-layout=deb
```

`checkinstall` may fail, but it'll leave a DEB file behind.  Install it with `sudo apt --fix-broken install ./caffeine-ng*.deb` and it'll pull the dependencies again.

**Comment by WhyNotHugo** [comment]
This should likely be reported to the Debian/Ubuntu package maintainer. I don't maintain such packages myself.

**Comment by STrRedWolf** [comment]
I'll see where `checkinstall` is maintained (probably is Debian).
