### ISSUE TITLE
Maintenence status: looking for contributors

### ISSUE THREAD

**Issue by WhyNotHugo** [caffeine-ng/caffeine-ng#55]
I currently don't use any "automatic" screen blanking.

I just have the <kbd>Pause</kbd> key [mapped to "lock screen and turn it off"](https://gitlab.com/WhyNotHugo/dotfiles/-/blob/e7c32067/home/.config/sway/apps.conf#L41), and press that whenever I stand up from my laptop. This approach is far safer than a timeout (where the machine is unlocked for a few minutes for anyone to access), and more power-efficient too.

At the same time, this suppresses the need to run a daemon to auto-lock the screen, and also suppresses my need for caffeine (wow, so much simpler!). 

I haven't used caffeine-ng in years, and maintaining it has become a burden. In great deal, because it supports a variety of platforms and tools that I don't even run any more, so testing simple fixes become a burden.

**I'm happy to provide feedback on PRs, help understand the code, narrow down bugs, and publish releases, but won't be writing code directly myself because of this.**

I've been holding off posting this for ages, since I wanted to do some good cleanups that I had in mind, but, honestly, I don't know if that's ever gonna happen due to priorities and times.

**Comment by ryerrappa** [comment]
Thanks for all you've done!
