### ISSUE TITLE
pavucontrol is mistakenly considered playing audio

### ISSUE THREAD

**Issue by diaasami** [caffeine-ng/caffeine-ng#60]
OS: Manjaro
Version: 3.5.1

`pavucontrol` is an application to monitor other apps playing and recording audio, it doesn't play audio on its own AFAIK, however as you can see below from the command-line output, caffeine-ng prohibits screensavers because of pavucontrol.

```
/usr/lib/python3.9/site-packages/caffeine/main.py:61: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
INFO:caffeine.core:Caffeine is starting up...
INFO:caffeine.core:Audio playback detected (pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol, pavucontrol). Inhibiting.
INFO:caffeine.core:XdgPowerManagmentInhibitor is applicable, state: True
INFO:caffeine.core:XorgInhibitor is applicable, state: True
INFO:caffeine.core:XdgScreenSaverInhibitor is applicable, state: True
INFO:caffeine.core:DpmsInhibitor is applicable, state: True
INFO:caffeine.core:
```

**Comment by VoodaGod** [comment]
this problem should be fixable with #57 which is in master. you can either blacklist pavucontrol or enable the peak filtering to ignore applications that are silent

**Comment by diaasami** [comment]
Then I think you can close the issue WONTFIX as it is an expected behavior.

**Comment by WhyNotHugo** [comment]
`pavucontrol` will prevent streams from suspending. Some more discussion on this here: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/892#note_502112

You can ignore `pavucontrol` thanks to #57. It should probably be on a "default ignore list".

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/60
