### ISSUE TITLE
[AUR] Dependencies Issue

### ISSUE THREAD

**Issue by M1ndo** [caffeine-ng/caffeine-ng#63]
- In The AUR PKGBUILD Dependency **python-pulsectl** is not on the official arch repos thus can't resolve all dependencies and the build fails.

**Comment by WhyNotHugo** [comment]
This package is in AUR: https://aur.archlinux.org/packages/python-pulsectl.

You  might want an AUR helper that does dependency resolution for you (e.g.: `paru`).
