### ISSUE TITLE
Dpms is inhibited even if DpmsInhibitor state is False

### ISSUE THREAD

**Issue by smartlitchi** [caffeine-ng/caffeine-ng#64]
On Archlinux, the package got updated from v3.5.1 to commit https://github.com/caffeine-ng/caffeine-ng/commit/683d5dc445a3b5d27535b0e9c60cb483a680fcb3. Since then, caffeine inhibits dpms even if the logs say otherwise
```
INFO:caffeine.core:Desired state is: DesiredState.UNINHIBITED
INFO:caffeine.core:XorgInhibitor is applicable, state: False
INFO:caffeine.core:DpmsInhibitor is applicable, state: False
```
If I revert back to v3.5.1, everything is fine.

**Comment by WhyNotHugo** [comment]
I believe this is the same as #61. Let's continue discussion there.
