### ISSUE TITLE
allow to send a signal to caffeine to activate / deactivate

### ISSUE THREAD

**Issue by steinex** [caffeine-ng/caffeine-ng#7]
Hi,

it would be desirable if caffeine-ng would have something like this implemented:

* Activate/Deactivate upon SIGUSR1/SIGUSR2 or such. That would enable users to deactivate caffeine on suspend via suspend hooks. This is my favorite, since there would be no need to do something like `su - -l $USER -s "caffeine -d"` in suspend hook.
* Make `caffeine -a` or `caffeine -d` actually do what they advertise to an already running instance.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/7
