### ISSUE TITLE
Give a more meaningfull reason of why the session is being inhibited

### ISSUE THREAD

**Issue by carlocastoldi** [caffeine-ng/caffeine-ng#78]
https://github.com/caffeine-ng/caffeine-ng/blob/1e5febf86a792edd5627f5e50e048be0848bd185/caffeine/inhibitors.py#L26

As of now the reason caffeine-ng gives the DEs for why the session should not be suspended is just `"Inhibited via libcaffeine"`. I suggest to get a text based on the enabled triggers, shown based on a given priority such as:
1. manually disabled
2. whitelisted program detected (<name_of_the_program>)
3. fullscreen program detected (<name_of_the_video_player>)
4. audio output detected (<name_of_the_audio_player>)
5. audio recording detected (<name_of_the_recording_program>)

**Comment by WhyNotHugo** [comment]
Is this reason displayed anywhere?

**Comment by carlocastoldi** [comment]
it is for me on KDE and, afaik, on gnome it is displayed when you try to log off.
Since it's possible to know, it would be nice to know _why_ my system is not being suspended without having to restart caffeine in `--verbose` mode

![immagine](https://user-images.githubusercontent.com/34198340/135754674-dcd3fc9d-36e7-4670-81b1-4ec402a086c5.png)

**Comment by jarrard** [comment]
I think my libcaffeine issue fixed itself after a reboot or update, or something.

Only shows up now when firefox plays audio which is correct behavior. And I think xscreensaver works accordingly.

 There is a minor suspend issue with steam interface but that is being handled over on steamforlinux github.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/78
