### ISSUE TITLE
Clementine + Caffeine

### ISSUE THREAD

**Issue by wolfyrion** [caffeine-ng/caffeine-ng#80]
It seems that sometimes Clementine activates Caffeine with or without Audio peak filtering.
This is happening  also even if I add Clementine in the list of audio detection.

BTW the old caffeine without the audio detection was working fine.

Thanks!

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/80
