### ISSUE TITLE
Desktop file should not include `/usr/bin/`

### ISSUE THREAD

**Issue by WhyNotHugo** [caffeine-ng/caffeine-ng#88]
It should be assumed that `caffeine` is in `$PATH`.

This facilitates setting up things like firejail.

**Comment by pietryszak** [comment]
When I use manual install, caffeine is installed in` /usr/local/bin/,` so desktop file has wrong path /usr/bin.

After change in .desktop to  `exec=caffeine` everything works fine.

Bug confirmed.

**Comment by WhyNotHugo** [comment]
Leaving this open since the preferences desktop file is still broken.

**Comment by pietryszak** [comment]
> Leaving this open since the preferences desktop file is still broken.

@WhyNotHugo Caffeine desktop file working fine, but preferences desktop not.
