### ISSUE TITLE
activate / desactivate caffeine by a global hotkey

### ISSUE THREAD

**Issue by Artiom-M** [caffeine-ng/caffeine-ng#9]
Hi,

it would be desirable if caffeine-ng would enable users to deactivate it by a hotkey. Alternatively if you make caffeine -a or caffeine -d actually do what they advertise to an already running instance uses would be able to define a hotkey using his desktop environment.

**Comment by Artiom-M** [comment]
Here is my quick patch for the hotkey activation. It uses python3-keybinder module.

[caff.patch.txt](https://github.com/caffeine-ng/caffeine-ng/files/2441757/caff.patch.txt)

I am not familiar with GTK development in order to provide something more useful but from my point of view the only missing thing is the hotkey configuration field in the options.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/9
