### ISSUE TITLE
Not working on KDE Plasma from the Panel

### ISSUE THREAD

**Issue by torma616** [caffeine-ng/caffeine-ng#95]
Hello,

This used to be working from the KDE Plasma panel either via clicking the icon directly (status_icon) or via dropdown (appindicator), but for a while now it hasn't worked from either. I can't find a way to activate/deactivate this (save for caffeine kill and starting from cli).

If this behaviour is intentional moving forward, please feel free to close this issue. However, in my eyes, this doesn't seem to be working as intended.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/95
