### ISSUE TITLE
[Feature request] Allow caffeine to be activated by single left click

### ISSUE THREAD

**Issue by Piulinux** [caffeine-ng/caffeine-ng#99]
Hey, I really like your application as it's pretty useful.
Would you mind to add an option in the preferences that the inhibition of the automatic screen locking can be activated with a left click on the tray icon (while right click continues to have the old behaviour)?

**Comment by WhyNotHugo** [comment]
This is, AFAIK, not supported by AppIndicators, so applications can't implement this.

**Comment by shuvashish76** [comment]
Suggestion:
Isn't it possible to point mouse cursor to Caffeine-ng tray icon & "Enable" by scrolling up ; "Disable" by scrolling down, just like we increase/decrease volume from system tray?

Ok, this is not same as @Piulinux 's feature request but IMO mouse scroller to control application is easier & more productive for users.

**Comment by WhyNotHugo** [comment]
>  Isn't it possible to point mouse cursor to Caffeine-ng tray icon (no clicks) & "Enable" by scrolling up ; "Disable" by scrolling down, just like we increase/decrease volume from system tray?

I don't think this is possible for AppIndicators. Any examples of applications that do this?

**Comment by shuvashish76** [comment]
> I don't think this is possible for AppIndicators. Any examples of applications that do this?

On my desktop, this is the only application. [Xfce PulseAudio Panel Plugin](https://docs.xfce.org/panel-plugins/xfce4-pulseaudio-plugin/start)
I think all other similar volume control apps does the same thing.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/99
